name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Load Dependency
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh && rustup toolchain install nightly && rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Run Build dev
        run: wasm-pack build --target web
      - name: Run Build release
        run: wasm-pack build --target web --release